# Generated by https://github.com/Yonsm/MiService
# http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:airer:0000A00D:mrbond-m1pro:1

from enum import IntEnum

SRV_Device_Information = 1
PROP_Device_Manufacturer = 1
PROP_Device_Model = 2
PROP_Device_Serial_Number = 3
PROP_Current_Firmware_Version = 4

SRV_Airer = 2
PROP_Motor_Control = 1 #uint8 #w
class VALUE_Motor_Control(IntEnum):
    Pause = 0
    Up = 1
    Down = 2
PROP_Dryer = 2 #bool #rw
PROP_Drying_Level = 3 #uint8 #rwn
class VALUE_Drying_Level(IntEnum):
    Level1 = 1
    Level2 = 2
    Level3 = 3
    Level4 = 4
PROP_Drying_Time = 4 #uint8
class VALUE_Drying_Time(IntEnum):
    MIN = 0
    MAX = 255

SRV_Light = 3
PROP_Switch_Status = 1 #bool #rwn

#, 3: 'Drying_Level', 4: 'Drying_Time'
ALL_PROPS = {1: {1: 'Device_Manufacturer', 2: 'Device_Model', 3: 'Device_Serial_Number', 4: 'Current_Firmware_Version'}, 2: {2: 'Dryer'}, 3: {1: 'Switch_Status'}}

